
CONFIG_ADC=n
#CONFIG_ADC_DEBOUNCE=n
#CONFIG_ADC_DEBOUNCE_SAMPLE_SIZE=100
#CONFIG_ADC_DEBOUNCECADENCE=1

CONFIG_USE_BUTTON=y
CONFIG_USE_GPIO_LED=n
CONFIG_USE_PWM_LED=n
CONFIG_USE_READY_LED=n
#CONFIG_USE_READY_LED_PWM=n
#CONFIG_USE_READY_LED_STRIP=n

CONFIG_USE_MOTION_SENSOR=n
CONFIG_USE_SEVEN_SEGMENT_DISPLAY=n
CONFIG_USE_FOUR_ELEMENT_SEVEN_SEGMENT_DISPLAY=n
